#' Given the factors and factor loadings, simulate the data
#'
#' @param model The data generated by the generateModel function
#' @param n number of units
#' @param trt treatment indicator vector
#' @param k_total number of outcomes
#' @param t_total number of pre-treatment periods
#' @param variance variance of the noise term
#' @param num_timepoints Number of training timepoints to use. Defaults to t_total.
#' @param embedding_dim  Dimension into which the matrix Q embeds the donors, ie, num synthetic donors
#' @param ortho Should the method be run using orthogonal matrix Q
#' @param qual aspect of the data to which the embedding be applied - donors or outcomes.
#'
#' @export
fit_models <- function(model,n,trt,k_total,t_total,variance, num_timepoints=NULL,embedding_dim,ortho, qual) {

  python_path <- system.file("python", package = "SDmethod")
  morph <- reticulate::import_from_path("morphData", path = python_path)
  lqorth <- reticulate::import_from_path("learnQorthogonal", path = python_path)
  lqsynth <- reticulate::import_from_path("synthOutcomesQ", path = python_path)
  lq <- reticulate::import_from_path("learnQ", path = python_path)

  # Use only first num_timepoints if specified
  if (!is.null(num_timepoints) & t_total == 40) {
    t_train <- num_timepoints
  } else {
    t_train <- t_total
  }

  epsilon <- matrix(rnorm((n * t_train) * k_total, sd = sqrt(variance)), ncol = k_total)
  out <- model[1:(n * t_train),] + epsilon # (NXT) x (K) matrix of outcomes
  t_trt <- rep(trt,t_train) # select the periods for the treated unit
  out_trt <- matrix(out[which(t_trt==1),],nrow = t_train,ncol =k_total)  # T x K matrix of outcomes for the treated unit
  out_control <- out[which(t_trt==0),] # ((N-1)xT) x (K) matrix of outcomes for the control units



  ## calculate SCM weights
  out_trt_sep <- out_trt[,1]
  out_control_sep <- matrix(out_control[,1], nrow = n-1,ncol=t_train)
  w_sep <- reticulate::py_to_r(synth_qp(out_trt_sep, out_control_sep))
  r.svd <- svd(rbind(out_control_sep,out_trt_sep))
  largest_svd <- r.svd$d[1]^2/sum(r.svd$d^2)
  cond <-  r.svd$d[1]/r.svd$d[t_train]

  out_trt_cat <- matrix(out_trt, nrow = t_train*k_total, ncol = 1)
  out_control_cat <- matrix(out_control, nrow = n-1,ncol=t_train*k_total)
  w_cat <- reticulate::py_to_r(synth_qp(out_trt_cat, out_control_cat))
  r.svd <- svd(rbind(out_control_cat,t(out_trt_cat)))
  largest_svd <- cbind(largest_svd, r.svd$d[1]^2/sum(r.svd$d^2))
  cond <- cbind(cond,  r.svd$d[1]/r.svd$d[length(r.svd$d)])

  out_trt_avg <- rowMeans(out_trt)
  out_control_avg <- matrix(rowMeans(out_control), nrow = n-1,ncol=t_train)
  w_avg <- reticulate::py_to_r(synth_qp(out_trt_avg, out_control_avg))
  r.svd <- svd(rbind(out_control_avg,t(out_trt_avg)))
  largest_svd <- cbind(largest_svd, r.svd$d[1]^2/sum(r.svd$d^2))
  cond <- cbind(cond,  r.svd$d[1]/r.svd$d[t_total])

  ### ### ### ### adding my method here ### ### ### ###

  treated_data <- out_trt
  control_data <- out_control

  result <- morph$morph(treated_data, control_data)

  # when this was not as.matrix wrapping these things would run sometimes...but would
  # often get a "object is from previous session error"
  train_target_vectors <- reticulate::py_to_r(result[[1]])
  train_covariate_matrices <- reticulate::py_to_r(result[[2]])
  test_target_vector <- reticulate::py_to_r(result[[3]])
  test_covariate_matrix <- reticulate::py_to_r(result[[4]])

  # targets, covariates, embedding_dim=embedding_dim, n_iterations=1000,
  # reg_Q=0, reg_w=0, verbose=True, num_timepoints = T,ortho=False
  if (qual == "outcomes") {
    result <- lqsynth$synthOutcomes(train_target_vectors, train_covariate_matrices, as.integer(embedding_dim), 1000L, 0,0, FALSE,NULL,FALSE)

  } else {
    if (ortho == FALSE) {
      # defaults to embedding dimension of 10.
      result <- lq$learnQ(train_target_vectors, train_covariate_matrices,10L, 1000L, 1.0, 10.0, verbose=FALSE)
    } else {
      result <- lqorth$learnQorthogonal(train_target_vectors, train_covariate_matrices, as.integer(embedding_dim), 1000L, 0.0, 0.0, FALSE, NULL, "eye", FALSE)
    }

  }


  Q_matrix <- reticulate::py_to_r(result[[1]])
  w_learnQ <- reticulate::py_to_r(result[[2]])


  ## calculate bias
  model_t1 <- model[((n * t_total)+1):(n * (t_total+1)),]

  # we use the Q_weights just as w_sep, w_cat, w_avg
  if (qual == "donors") {
    Q_weights <- Q_matrix %*% w_learnQ
    oracle_bias_Q   <- as.numeric(reticulate::py_to_r(SCMbias(model_t1[-trt,1], model_t1[trt,1], Q_weights)))
  } else {
    oracle_bias_Q   <- as.numeric(reticulate::py_to_r(SCMbias(model_t1[-trt,1], model_t1[trt,1], w_learnQ)))
  }




  # just calculate the bias in the first outcome.

  oracle_bias_sep <- as.numeric(reticulate::py_to_r(SCMbias(model_t1[-trt,1], model_t1[trt,1], w_sep)))
  oracle_bias_cat <- as.numeric(reticulate::py_to_r(SCMbias(model_t1[-trt,1], model_t1[trt,1], w_cat)))
  oracle_bias_avg <- as.numeric(reticulate::py_to_r(SCMbias(model_t1[-trt,1], model_t1[trt,1], w_avg)))
  # Add bias calculation for Q weights here:


  # oracle_bias_sep <- SCMbias(model_t1[-trt,1],model_t1[trt,1],w_sep)
  # oracle_bias_cat <- SCMbias(model_t1[-trt,1],model_t1[trt,1],w_cat)
  # oracle_bias_avg <- SCMbias(model_t1[-trt,1],model_t1[trt,1],w_avg)

  # oracle_bias_Q <- SCMbias(model_t1[-trt,1],model_t1[trt,1],Q_weights) # this may not be the correct dimensions.

  return(list("oracle_bias" = c(oracle_bias_sep, oracle_bias_cat, oracle_bias_avg,as.numeric(oracle_bias_Q)), # added bias_Q
              "iter_time" = NULL
  ))
}
